In [2]:
## import pandas library 
import pandas as pd

In [4]:
#import data and store as data frame
ms2020_excerpt_df = pd.read_csv("data-raw/ems20_1st_6months_excerpt.csv")

In [8]:
#call the first 10 rows 
ms2020_excerpt_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [24]:
#call the last five rows
ms2020_excerpt_df.tail(5)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [12]:
## call a 20 random rows
ms2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
2193,201692153,2020-06-17 15:02:23,MEDRXN,5,MEDRXN,5,06/17/2020 03:02:34 PM,Y,11,06/17/2020 03:02:42 PM,...,42.0,16.0,203.0,9.0,15.0,N,N,N,N,chunk172.csv
9145,201362959,2020-05-15 18:24:58,CVAC,2,CVAC,2,05/15/2020 06:25:11 PM,Y,13,05/15/2020 06:25:17 PM,...,122.0,50.0,503.0,31.0,11.0,N,N,N,N,chunk170.csv
12367,200370478,2020-02-06 03:48:34,SICK,6,SICK,6,02/06/2020 03:48:44 AM,Y,10,02/06/2020 03:49:08 AM,...,71.0,41.0,309.0,17.0,9.0,N,N,N,N,chunk166.csv
10278,201413757,2020-05-20 23:31:47,CARD,3,CARD,3,05/20/2020 11:32:10 PM,Y,23,05/20/2020 11:32:31 PM,...,104.0,30.0,405.0,24.0,6.0,N,N,N,N,chunk171.csv
8147,200935825,2020-04-02 21:17:39,DIFFBR,2,DIFFBR,2,04/02/2020 09:19:19 PM,Y,100,04/02/2020 09:20:32 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk169.csv
936,201373907,2020-05-16 23:09:37,INJURY,5,INJURY,5,05/16/2020 11:10:29 PM,Y,52,05/16/2020 11:10:41 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk170.csv
9185,200344609,2020-02-03 20:57:53,UNKNOW,4,UNKNOW,4,02/03/2020 08:58:05 PM,Y,12,02/03/2020 08:58:17 PM,...,112.0,29.0,406.0,28.0,6.0,N,N,N,N,chunk166.csv
11251,200571889,2020-02-26 12:04:57,SICK,6,SICK,6,02/26/2020 12:05:10 PM,Y,13,02/26/2020 12:05:24 PM,...,81.0,36.0,303.0,16.0,8.0,N,N,N,N,chunk167.csv
995,201322074,2020-05-11 14:43:39,SICMIN,7,SICMIN,7,05/11/2020 02:44:15 PM,Y,36,05/11/2020 02:44:27 PM,...,67.0,41.0,317.0,17.0,9.0,Y,N,N,N,chunk170.csv
6693,201772451,2020-06-25 15:54:21,CARDBR,2,CARDBR,2,06/25/2020 03:54:31 PM,Y,10,06/25/2020 03:54:52 PM,...,112.0,29.0,406.0,28.0,6.0,N,N,N,N,chunk172.csv
9235,201182907,2020-04-27 18:40:45,CVAC,2,CVAC,2,04/27/2020 06:40:54 PM,Y,9,04/27/2020 06:42:31 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk170.csv
9664,201823749,2020-06-30 21:53:48,SHOT,3,SHOT,3,06/30/2020 09:54:19 PM,Y,31,06/30/2020 09:54:37 PM,...,73.0,42.0,316.0,23.0,9.0,N,N,N,N,chunk172.csv
170,200323090,2020-02-01 16:57:55,INJURY,5,INJURY,5,02/01/2020 04:58:57 PM,Y,62,02/01/2020 04:59:30 PM,...,13.0,4.0,106.0,2.0,12.0,N,N,N,N,chunk166.csv
6614,201541523,2020-06-02 11:34:56,INJURY,5,INJURY,5,06/02/2020 11:35:43 AM,Y,47,06/02/2020 11:36:02 AM,...,63.0,46.0,318.0,22.0,8.0,N,N,N,N,chunk171.csv
8041,200936174,2020-04-02 22:30:23,DRUG,4,DRUG,4,04/02/2020 10:34:22 PM,Y,239,04/02/2020 10:34:27 PM,...,94.0,33.0,301.0,14.0,12.0,N,N,N,N,chunk169.csv
3650,201480165,2020-05-27 01:11:31,DIFFFC,2,DIFFFC,2,05/27/2020 01:12:09 AM,Y,38,05/27/2020 01:12:19 AM,...,69.0,46.0,318.0,18.0,8.0,N,N,N,N,chunk171.csv
10768,201202097,2020-04-29 15:39:30,EDP,7,EDP,7,04/29/2020 03:40:23 PM,Y,53,04/29/2020 03:40:32 PM,...,111.0,23.0,411.0,26.0,6.0,N,N,N,N,chunk170.csv
7018,200673961,2020-03-07 22:19:00,UNC,2,ARREST,1,03/07/2020 10:20:23 PM,Y,83,03/07/2020 10:20:31 PM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
10763,201711694,2020-06-19 12:45:40,EDP,7,EDP,7,06/19/2020 12:45:48 PM,Y,8,06/19/2020 12:46:04 PM,...,46.0,16.0,205.0,9.0,13.0,N,N,N,N,chunk172.csv
1206,200660657,2020-03-06 05:18:27,INJURY,5,INJURY,5,03/06/2020 05:18:30 AM,Y,3,03/06/2020 05:18:40 AM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk167.csv

In [14]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
ms2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [16]:
#There are integers, objects, and floats
#There are 32 columns

In [18]:
## call the top 7 rows
ms2020_excerpt_df.head(7)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv

In [20]:
## call a sample of 10
ms2020_excerpt_df.sample(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
4403,201163702,2020-04-25 22:24:44,OTHER,6,EDPC,7,04/25/2020 10:25:03 PM,Y,19,04/25/2020 10:25:11 PM,...,46.0,14.0,205.0,9.0,15.0,N,N,N,N,chunk170.csv
138,201004005,2020-04-09 17:31:24,CDBRFC,2,CDBRFC,2,04/09/2020 05:31:33 PM,Y,9,04/09/2020 05:31:46 PM,...,68.0,43.0,310.0,20.0,11.0,N,N,N,N,chunk169.csv
1528,200143685,2020-01-14 18:45:20,RESPIR,4,DIFFBR,2,01/14/2020 06:47:17 PM,Y,117,01/14/2020 06:47:39 PM,...,84.0,33.0,302.0,15.0,7.0,N,N,N,N,chunk165.csv
11272,200340026,2020-02-03 00:06:53,SICK,6,SICK,6,02/03/2020 12:07:05 AM,Y,12,02/03/2020 12:07:16 AM,...,23.0,5.0,111.0,2.0,13.0,N,N,N,N,chunk166.csv
7132,201730636,2020-06-21 03:48:36,MCI21,2,MCI21,2,06/21/2020 03:48:45 AM,Y,9,06/21/2020 03:48:54 AM,...,109.0,24.0,407.0,25.0,6.0,N,N,N,N,chunk172.csv
6637,200260747,2020-01-26 04:41:50,DIFFBR,2,CARDBR,2,01/26/2020 04:42:01 AM,Y,11,01/26/2020 04:42:35 AM,...,69.0,46.0,318.0,18.0,8.0,N,N,N,N,chunk166.csv
2941,200974796,2020-04-06 17:15:47,SICMIN,7,SICMIN,7,04/06/2020 05:28:56 PM,Y,789,04/06/2020 05:29:05 PM,...,105.0,27.0,413.0,29.0,5.0,N,N,N,N,chunk169.csv
10996,201383095,2020-05-17 20:41:56,DRUG,4,DRUG,4,05/17/2020 08:43:00 PM,Y,64,05/17/2020 08:43:50 PM,...,105.0,23.0,413.0,26.0,3.0,N,N,N,N,chunk171.csv
724,200794578,2020-03-19 21:12:02,EDP,7,EDPC,7,03/19/2020 09:12:18 PM,Y,16,03/19/2020 09:12:25 PM,...,114.0,22.0,401.0,30.0,12.0,N,N,N,N,chunk168.csv
12325,201160525,2020-04-25 04:30:20,CARD,3,CARD,3,04/25/2020 04:30:25 AM,Y,5,04/25/2020 04:30:46 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk170.csv

In [22]:
## call the bottom 6
ms2020_excerpt_df.tail(6)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13111,200870168,2020-03-27 00:42:59,INJURY,5,INJURY,5,03/27/2020 12:43:13 AM,Y,14,03/27/2020 12:43:28 AM,...,109.0,19.0,407.0,25.0,3.0,N,N,N,N,chunk168.csv
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [26]:
## Programmatically capture the 2245th FINAL_CALL_TYPE value and store in a variable.
target_value = ms2020_excerpt_df["FINAL_CALL_TYPE"].iat[2244]

In [28]:
target_value

'STAB'

In [100]:
## import Excel data here
cbp_df = pd.read_excel("data-raw/multi-data.xlsx", sheet_name = 2, skiprows = 6)

In [104]:
## call the top 15 rows
cbp_df.head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [106]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
cbp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB

In [40]:
# The data types are floats, objects, and datetimes 
#There are 9 columns and 95721 rows

In [108]:
## call the bottom 3
cbp_df.tail(3)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [110]:
## call a sample of 20
cbp_df.sample(20)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
76037,2018-04-08 21:30:00,2018-04-10 13:31:00,40.000000,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
74665,2018-04-03 12:00:00,2018-04-03 16:47:00,4.766667,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
39598,2017-11-12 19:22:00,2017-11-14 11:45:00,40.366667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
26965,2017-09-06 16:00:00,2017-09-08 05:10:00,37.150000,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
41613,2017-11-20 14:29:00,2017-11-22 11:11:00,44.700000,15-18 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
74772,2018-04-03 19:35:00,2018-04-05 11:06:00,39.500000,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
23987,2017-08-21 17:50:00,2017-08-23 15:45:00,45.900000,3-5 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
73988,2018-03-30 23:35:00,2018-04-03 08:56:00,81.333333,1-2 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
58442,2018-01-27 20:00:00,2018-01-28 16:39:00,20.616667,15-18 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
39175,2017-11-10 20:55:00,2017-11-13 14:25:00,65.483333,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
67920,2018-03-11 01:15:00,2018-03-14 09:32:00,80.266667,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
26979,2017-09-06 18:26:00,2017-09-08 00:04:00,29.633333,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
10714,2017-05-03 20:30:00,2017-05-05 08:52:00,36.350000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
37468,2017-11-03 15:40:00,2017-11-06 17:20:00,73.650000,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
63766,2018-02-22 00:15:00,2018-02-24 15:33:00,63.283333,3-5 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
67491,2018-03-09 20:50:00,2018-03-12 10:47:00,61.933333,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
53574,2018-01-06 18:00:00,2018-01-07 15:52:00,21.866667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
43971,2017-11-28 18:50:00,2017-11-30 03:55:00,33.066667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8414,2017-03-21 21:00:00,2017-03-22 12:37:00,15.600000,3-5 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
20254,2017-07-31 01:59:00,2017-07-31 07:51:00,5.866667,15-18 years,Female,MEXICO,SBO,(b)(7)(E ),NaN

In [115]:
## Programmatically capture the 8th hours_in_custody value and store in a variable.
target_value = cbp_df["hours_in_custody"].iat[7]

In [117]:
target_value

14.6333333333333